resilience4j:
  retry:
    retry-aspect-order: 399     #表示retry的优先级 高于限流，断路器 数值越小优先级越高
    backends:
      retryA:
        maxRetryAttempts: 5   #重试次数
        waitDuration: 500     #重试的等待时间  500ms
        exponentialBackoffMultiplier: 1.1 #间隔乘数
        retryExceptions:
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
       cbA:
        ringBufferSizeInHalfOpenState: 3   #当断路器处于half open 状态时，环形缓冲区的大小
        ringBufferSizeInClosedState: 5     #断路器处于关闭状态时，环形缓冲区的大小
        waitInterval: 5000                #时间间隔
        recordExceptions:                 #异常
          - org.springframework.web.client.HttpServerErrorException
    circuit-breaker-aspect-order: 398
server:
  port: 5000
spring:
  application:
    name:  resilience4j
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka



